version: '3.8'
services:
  mysqldb:
    image: mysql:9.0.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=order-management
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - order-management-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data:
networks:
  order-management-network:
    name: order-management-network
